spring:
    application:
        name: utsukushii

server:
  port: 8092

utsukushii:
  id: SingleParamSet # used to retrieve from mongo
  name: Team-0
  accessCode: dogornose
  rabbitUrl: ${FNF_SERVER}
  mongoUrl: localhost
  mongoDb: utsukushii
  plotSensor: true

  constantPowerProperties:
    teamId: Utsukushii
    accessCode: letmein
    frequencyInHertz: 5

  trackDetectionProperties:
    primaryFilterSize: 3
    upperStraightBoundary: 1000
    lowerStraightBoundary: -1000
    triggerSize: 3
    gradientThreshold: 30.0
    kickFactor: 2.0

  trackModelActorProperties:
    minStraightLength: 160 # milliseconds
    minNumberOfCurves: 4 # expect at least four major curves
    awaitSectionsBeforeRecognition: 6 # let 3 sections pass by before starting track recognitions

  loggingReceiverProperties:
    publishEveryAfter: 5000

  replayProperties:
    frequency: 50
