spring:
    application:
        name: utsukushii

server:
  port: 8092

javapilot:

    name: Team-0
    accessCode: dogornose

    rabbitUrl: ${FNF_SERVER}

    constantPowerProperties:
      frequencyInHertz: 5